services:
  zookeeper-event-manager:
    image: confluentinc/cp-zookeeper:7.8.9
    container_name: zookeeper-event-manager
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"

  kafka-event-manager:
    image: confluentinc/cp-kafka:7.8.9
    container_name: kafka-event-manager
    depends_on:
      - zookeeper-event-manager
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-event-manager:2182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: "true"
    ports:
      - "9093:9093"