server:
  port: 8080

spring:
  application:
    name: event-manager-service

  datasource:
    url: jdbc:postgresql://localhost:5434/event-manager-service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    enabled: true
    url: /event-manager-openapi.yaml
  api-docs:
    enabled: true