server:
  port: 8080

spring:
  application:
    name: event-manager-service
  profiles:
    active: dev

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    enabled: true
    url: /event-manager-openapi.yaml
  api-docs:
    enabled: true

scheduled:
  fixed-rate:
    event-status: 1m